artifact_root: artifacts

data_ingestion:
    download_url: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

data_transformation:
    tokenizer_name: google/pegasus-cnn_dailymail
    dataset_dir: artifacts/data_ingestion/samsum_dataset
    save_to_dir: artifacts/data_transformation/samsum_dataset

model_trainer:
    model_name: google/pegasus-cnn_dailymail 
    dataset_dir: artifacts/data_transformation/samsum_dataset
    model_save_to_dir: artifacts/model_trainer/model
    tokenizer_save_to_dir: artifacts/model_trainer/tokenizer
